
site_name: 'node-7-38-pm'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/nishant-shah-anblicks/node-7-38-pm
edit_uri: edit/master/docs

plugins:
  - techdocs-core
nav:
  - Overview:
      - What is Backstage?: './README.md'

  - Support:
  - FAQ: 
